import type { Metadata } from "next";
import localFont from "next/font/local";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Vistanesia",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
        <Toaster richColors />
      </body>
    </html>
  );
}
